/* eslint-disable react/jsx-key */
import Head from 'next/head'
import LandingPage from '../components/landingPage.jsx'
import Welcome from '../components/Welcome.jsx'
import OurLabs from '../components/ourLabs.jsx'
import AboutUsHome from '../components/aboutUsHome.jsx'
import Carousel from '../components/carouselComp.jsx'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
      <Welcome />
      <OurLabs />
      {/* <Carousel /> */}
      {/* <AboutUsHome /> */}
    </div>
  )
}
